# Default values for indexer-deploy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

data:
  requestsCpu: "0.1"
  requestsMemory: "640M"
  limitsCpu: "1"
  limitsMemory: "1G"
  image: ""
  imagePullPolicy: "IfNotPresent"
  serviceAccountName: "indexer"

conf:
  appName: "indexer"
  configmap: "indexer-config"
  elasticSecretName: "indexer-elastic-secret"
  keycloakSecretName: "indexer-keycloak-secret"
  rabbitmqSecretName: "rabbitmq-secret"
  onPremEnabled: false
  domain: ""

istio:
  proxyCPU: "50m"
  proxyCPULimit: "500m"
  proxyMemory: "64Mi"
  proxyMemoryLimit: "512Mi"
