aws-test-java:
  extends:
    - .maven
    - .aws    
    - .aws_common_variables
    - .aws_variables
  stage: integration
  needs: [{ job: 'aws-update-tf', optional: true }, { job: 'aws-update-helm', optional: true }, { job: 'aws-update-eks', optional: true }]
  retry: 1
  before_script:
    - !reference [.maven, before_script]
    - !reference [.aws, before_script]
    - !reference [.aws_variables, before_script]
  script:
    - echo os-indexer override
    - export ELASTIC_HOST=localhost
    - export KUBECONFIG=/tmp/kubeconfig-${RANDOM}.yaml
    - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME --role-arn $EKS_CLUSTER_MGMT_ROLE

    - localPort=$ELASTIC_PORT
    - echo $localPort
    - kubectl port-forward -n $TENANT_GROUP_NAME-tenant-$EKS_TENANT_NAME-elasticsearch svc/elasticsearch-es-http $localPort:$ELASTIC_PORT > /dev/null 2>&1 &
    - export ELASTIC_PORT=$localPort
    - pid=$!
    - |
      trap '{
        echo killing "Port forward process: "$pid
        kill $pid
        rm $KUBECONFIG
      }' EXIT
    - $MAVEN_BUILD $INTEGRATION_TEST_DIR maven-aws-integration-test-output.txt ${AWS_MAVEN_TEST_COMMAND_OVERRIDE:-test} --update-snapshots -DdisableXmlReport=true
  only:
    variables:
      #Default if not defined
      - $AWS_SKIP_DEPLOY != 'true' && $AWS_SKIP_TESTS != 'true' && $AWS == '1' && ($AWS_INT_TEST_TYPE == 'java' || $AWS_INT_TEST_TYPE == null)
  artifacts:
      when: always
      paths:
        - $INTEGRATION_TEST_DIR
      expire_in: 2 days
