variables:
  AWS_BUILD_SUBDIR: provider/indexer-aws/build-aws
  AWS_TEST_SUBDIR: testing/indexer-test-aws
  AWS_SERVICE: indexer
  AWS_ENVIRONMENT: dev

  GCP_BUILD_SUBDIR: provider/indexer-gcp
  GCP_INT_TEST_SUBDIR: testing/indexer-test-gcp
  GCP_APPLICATION_NAME: osdu-indexer
  GCP_ENVIRONMENT: dev
  GCP_PROJECT: opendes
  GCP_TENANT_NAME: opendes
  GCP_DEPLOY_ENV: p4d
  GCP_DOMAIN: cloud.slb-ds.com
  GCP_STORAGE_URL: https://osdu-indexer-dot-opendes.appspot.com/api/storage/v2/

  OSDU_GCP_BUILD_SUBDIR: provider/indexer-gcp
  OSDU_GCP_INT_TEST_SUBDIR: testing/indexer-test-gcp
  OSDU_GCP_APPLICATION_NAME: os-indexer
  OSDU_GCP_PROJECT: nice-etching-277309
  OSDU_GCP_TENANT_NAME: osdu
  OSDU_GCP_SCHEMA_HOST: https://os-schema-dot-nice-etching-277309.uc.r.appspot.com/api/schema-service/v1/schema
  OSDU_SECURITY_HTTPS_CERTIFICATE_TRUST: 'true'

  IBM_BUILD_SUBDIR: provider/indexer-ibm
  IBM_INT_TEST_SUBDIR: testing/indexer-test-ibm

  AZURE_SERVICE: indexer
  AZURE_BUILD_SUBDIR: provider/indexer-azure
  AZURE_TEST_SUBDIR: testing/indexer-test-azure

include:
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "build/maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/fossa.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/gitlab-ultimate.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/aws.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/azure.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/ibm.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "publishing/pages.yml"

  - project: 'osdu/platform/ci-cd-pipelines'
    ref: "master"
    file: 'cloud-providers/osdu-gcp.yml'


aws-test-java:
  tags: ['aws-internal-test']
