apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.conf.appName | quote }}
    type: core
    source: java
  name: {{ .Values.conf.appName | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.conf.appName | quote }}
  replicas: {{ .Values.conf.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.conf.appName | quote }}
        sidecar.istio.io/inject: {{ .Values.istio.sidecarInject | quote }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        sidecar.istio.io/proxyCPU: {{ .Values.istio.proxyCPU | quote }}
        sidecar.istio.io/proxyMemory: {{ .Values.istio.proxyMemory | quote }}
        sidecar.istio.io/proxyCPULimit: {{ .Values.istio.proxyCPULimit | quote }}
        sidecar.istio.io/proxyMemoryLimit: {{ .Values.istio.proxyMemoryLimit | quote }}
        ### FIXME traffic.sidecar.istio.io - This is strictly a temporary solution until the task GONRG-8825 is completed
        traffic.sidecar.istio.io/excludeOutboundPorts: "80"
    spec:
    ### FIXME initContainers - This is strictly a temporary solution until the task GONRG-8825 is completed
      initContainers:
      - name: init
        image: gcr.io/osdu-anthos/indexer/gc-indexer-init:temp
        imagePullPolicy: {{ .Values.data.imagePullPolicy | quote }}
      containers:
      - name: {{ .Values.conf.appName | quote }}
        image: {{ .Values.data.image | quote }}
        imagePullPolicy: {{ .Values.data.imagePullPolicy | quote }}
        env:
        - name: REDIS_GROUP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.conf.indexerRedisSecretName | quote }}
              key: REDIS_PASSWORD
        - name: REDIS_SEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.conf.indexerRedisSecretName | quote }}
              key: REDIS_PASSWORD
        envFrom:
        - configMapRef:
            name: {{ .Values.conf.configmap | quote }}
        - secretRef:
            name: {{ .Values.conf.elasticSecretName | quote }}
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
        ports:
        - containerPort: 8080
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/liveness
            port: 8081
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 20
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /health/readiness
            port: 8081
            scheme: HTTP
          periodSeconds: 15
        resources:
          requests:
            cpu: {{ .Values.data.requestsCpu | quote }}
            memory: {{ .Values.data.requestsMemory | quote }}
          {{- if .Values.global.limitsEnabled }}
          limits:
            cpu: {{ .Values.data.limitsCpu | quote }}
            memory: {{ .Values.data.limitsMemory | quote }}
          {{- end }}
      serviceAccountName: {{ .Values.data.serviceAccountName | quote }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
