{{ if not .Values.data.redisIndexerHost }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "redis-%s" .Values.conf.appName | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
  - port: {{ .Values.data.redisIndexerPort }}
    protocol: TCP
    targetPort: 6379
    name: {{ printf "redis-%s-port" .Values.conf.appName | quote }}
  selector:
    app: {{ printf "redis-%s" .Values.conf.appName | quote }}
{{ end }}
