apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Values.conf.appName |  quote }}
  name: {{ .Values.conf.configmap | quote }}
  namespace: {{ .Release.Namespace | quote }}
data:
  ENTITLEMENTS_HOST: {{ .Values.data.entitlementsHost | quote }}
  INDEXER_QUEUE_BASE_HOST: {{ .Values.data.indexerQueueHost | quote }}
  LOG_LEVEL: {{ .Values.data.logLevel | quote }}
  PARTITION_HOST: {{ .Values.data.partitionHost | quote }}
  REDIS_GROUP_HOST: {{ .Values.data.redisGroupHost | quote }}
  REDIS_SEARCH_HOST: {{ .Values.data.redisSearchHost | quote }}
  SCHEMA_BASE_HOST: {{ .Values.data.schemaHost | quote }}
  SECURITY_HTTPS_CERTIFICATE_TRUST: {{ .Values.data.securityHttpsCertificateTrust | quote }}
  SPRING_PROFILES_ACTIVE: {{ .Values.data.springProfilesActive | quote }}
  STORAGE_HOST: {{ .Values.data.storageHost | quote }}
  
