# Default values for indexer-configmap.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

data:
  # common
  entitlementsHost: "http://entitlements"
  indexerQueueHost: "http://indexer-queue"
  logLevel: "ERROR"
  partitionHost: "http://partition"
  redisGroupHost: "redis-group-master"
  redisSearchHost: "redis-search-master"
  schemaHost: "http://schema"
  securityHttpsCertificateTrust: "true"
  springProfilesActive: "gcp"
  storageHost: "http://storage"
  # gcp
  googleAudiences: ""
conf:
  appName: "indexer"
  configmap: "indexer-config"
  onPremEnabled: false
