version: "3"
services:
  os-indexer-app:
    build:
      args: 
        JAR_FILE: target/indexer-gcp-1.0.4-SNAPSHOT-spring-boot.jar
      context: ..
      dockerfile: docker/Dockerfile
    image: gcr.io/opendes/os-indexer-app
    ports:
     - "8080:8080"

