variables:
  GC_SERVICE: indexer
  GC_VENDOR: gc

gc-test:
  variables:
    CUCUMBER_OPTIONS: "--tags ~@indexer-extended"

gc-baremetal-test:
  variables:
    GC_VENDOR: baremetal
    CUCUMBER_OPTIONS: "--tags ~@indexer-extended"
