variables:
  GC_SERVICE: indexer
  GC_VENDOR: gc

gc-test:
  variables:
    CUCUMBER_OPTIONS: "--tags @as-ingested-coordinates,@default,@bag-of-words,@keyword-lower,@indexer-extended"

gc-dev2-test:
  variables:
    CUCUMBER_OPTIONS: "--tags @as-ingested-coordinates,@default,@bag-of-words,@keyword-lower,@indexer-extended"
