apiVersion: v1
data:
  AUTHORIZE_API: ${AUTHORIZE_API}
  MONGO_DB_URL: ${MONGO_DB_URL}
  MONGO_DB_USER: ${MONGO_DB_USER}
  MONGO_DB_NAME: ${MONGO_DB_NAME}
  REGION: ${REGION}
  LEGALTAG_API: ${LEGALTAG_API}
  INDEXER_HOST: ${INDEXER_HOST}
  GOOGLE_CLOUD_PROJECT: ${GOOGLE_CLOUD_PROJECT}
  STORAGE_HOSTNAME: ${STORAGE_HOSTNAME}
  STORAGE_SCHEMA_HOST: ${STORAGE_SCHEMA_HOST}
  STORAGE_QUERY_RECORD_HOST: ${STORAGE_QUERY_RECORD_HOST}
  STORAGE_QUERY_RECORD_FOR_CONVERSION_HOST: ${STORAGE_QUERY_RECORD_FOR_CONVERSION_HOST}
  INDEXER_QUEUE_HOST: ${INDEXER_QUEUE_HOST}
  CRS_API: ${CRS_API}
  REDIS_GROUP_HOST: ${REDIS_GROUP_HOST}
  REDIS_SEARCH_HOST: ${REDIS_SEARCH_HOST}
  GOOGLE_AUDIENCES: ${GOOGLE_AUDIENCES}
  KEY_RING: ${KEY_RING}
  KMS_KEY: ${KMS_KEY}
kind: ConfigMap
metadata:
  labels:
    app: indexer-reference
  name: indexer-config
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  generateName: indexer-reference-anthos
  labels:
    app: indexer-reference
  name: indexer-reference
  namespace: default
spec:
  selector:
    matchLabels:
      app: indexer-reference
  replicas: 1
  template:
    metadata:
      labels:
        app: indexer-reference
    spec:
      containers:
        -   env:
              -   name: AUTHORIZE_API
                  valueFrom:
                    configMapKeyRef:
                      key: AUTHORIZE_API
                      name: indexer-config
              -   name: MONGO_DB_URL
                  valueFrom:
                    configMapKeyRef:
                      key: MONGO_DB_URL
                      name: indexer-config
              -   name: MONGO_DB_USER
                  valueFrom:
                    configMapKeyRef:
                      key: MONGO_DB_USER
                      name: indexer-config
              -   name: MONGO_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: indexer-secret
                      key: mongo.db.password
              -   name: MONGO_DB_NAME
                  valueFrom:
                    configMapKeyRef:
                      key: MONGO_DB_NAME
                      name: indexer-config
              -   name: MB_RABBITMQ_URI
                  valueFrom:
                    secretKeyRef:
                      name: indexer-secret
                      key: mb.rabbitmq.uri
              -   name: REGION
                  valueFrom:
                    configMapKeyRef:
                      key: REGION
                      name: indexer-config
              -   name: LEGALTAG_API
                  valueFrom:
                    configMapKeyRef:
                      key: LEGALTAG_API
                      name: indexer-config
              -   name: INDEXER_HOST
                  valueFrom:
                    configMapKeyRef:
                      key: INDEXER_HOST
                      name: indexer-config
              -   name: GOOGLE_CLOUD_PROJECT
                  valueFrom:
                    configMapKeyRef:
                      key: GOOGLE_CLOUD_PROJECT
                      name: indexer-config
              -   name: STORAGE_HOSTNAME
                  valueFrom:
                    configMapKeyRef:
                      key: STORAGE_HOSTNAME
                      name: indexer-config
              -   name: STORAGE_SCHEMA_HOST
                  valueFrom:
                    configMapKeyRef:
                      key: STORAGE_SCHEMA_HOST
                      name: indexer-config
              -   name: STORAGE_QUERY_RECORD_HOST
                  valueFrom:
                    configMapKeyRef:
                      key: STORAGE_QUERY_RECORD_HOST
                      name: indexer-config
              -   name: STORAGE_QUERY_RECORD_FOR_CONVERSION_HOST
                  valueFrom:
                    configMapKeyRef:
                      key: STORAGE_QUERY_RECORD_FOR_CONVERSION_HOST
                      name: indexer-config
              -   name: INDEXER_QUEUE_HOST
                  valueFrom:
                    configMapKeyRef:
                      key: INDEXER_QUEUE_HOST
                      name: indexer-config
              -   name: CRS_API
                  valueFrom:
                    configMapKeyRef:
                      key: CRS_API
                      name: indexer-config
              -   name: REDIS_GROUP_HOST
                  valueFrom:
                    configMapKeyRef:
                      key: REDIS_GROUP_HOST
                      name: indexer-config
              -   name: REDIS_SEARCH_HOST
                  valueFrom:
                    configMapKeyRef:
                      key: REDIS_SEARCH_HOST
                      name: indexer-config
              -   name: GOOGLE_AUDIENCES
                  valueFrom:
                    configMapKeyRef:
                      key: GOOGLE_AUDIENCES
                      name: indexer-config
              -   name: KEY_RING
                  valueFrom:
                    configMapKeyRef:
                      key: KEY_RING
                      name: indexer-config
              -   name: KMS_KEY
                  valueFrom:
                    configMapKeyRef:
                      key: KMS_KEY
                      name: indexer-config
            image: us.gcr.io/osdu-anthos-02/os-indexer/anthos-indexer-reference:9966597-dirty
            name: indexer-reference
---
apiVersion: v1
kind: Service
metadata:
  name: indexer-reference
  namespace: default
spec:
  ports:
    -   protocol: TCP
        port: 80
        targetPort: 8080
  selector:
    app: indexer-reference
  type: LoadBalancer
---
apiVersion: v1
data:
  mongo.db.password: ${mongo.db.password}
  mb.rabbitmq.uri: ${mb.rabbitmq.uri}
kind: Secret
metadata:
  name: indexer-secret
  namespace: default
type: Opaque