site_name: OSDU Indexer Service Documentation
site_description: OSDU Indexer Service
site_author: Shane Hutchins

# Repository
repo_url: https://community.opengroup.org/osdu/platform/system/indexer-service
repo_name: Indexer

# Copyright
copyright: Copyright &copy; 2024 Open Subsurface Data Universe Software

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

markdown_extensions:
  - admonition
  - sane_lists

plugins:
  - search
  - git-revision-date
